### ISSUE TITLE
pasta de imagens dissociada

### ISSUE THREAD

**Issue by ibiaalice** [giovanaBritoOliveira/HighScore#1]
no caso, adiciona uma pasta de imagens a cada parte do projeto. No real, as duas partes poderao esta sendo executadas em locais de diretorios diferentes e acabar gerando um conflito de busca. Alem de gerar colisao no uso do mesmo arquivo por dois processos diferentes :+1:

**Comment by g1ovanaqueiroz** [comment]
Resolvido, muito obrigada pela sugestão! ^^
