### ISSUE TITLE
Converter componentes de classe em componentes funcionais

### ISSUE THREAD

**Issue by alvesmatheus** [giovanaBritoOliveira/HighScore#2]
Oi, @giovanaBritoOliveira! :mage_man: Queria sugerir converter teus componentes atuais (baseados em classes) em componentes funcionais. [Aqui](https://pt-br.reactjs.org/docs/hooks-intro.html) tem uma introdução bem didática do React sobre como utilizá-los. 

Além de alinhar teu projeto à disciplina, vai reduzir a complexidade do desenvolvimento em várias frentes, como dispensando o uso dos `.bind()`, por exemplo. :merman:

**Comment by g1ovanaqueiroz** [comment]
Obrigada, @alvesmatheus! Vou sair corrigindo isso e outras coisas. ^^
