### ISSUE TITLE
Estados "curtido" e "não curtido" ambíguos em Comentario.js

### ISSUE THREAD

**Issue by lucasmedeiros** [giovanaBritoOliveira/HighScore#3]
Olá Giovana, tudo bem?

Gostei bastante do seu projeto, achei muito interessante! :notes: :sparkles: 

Fui vasculhar os componentes e lá em [components/Comentario.js](https://github.com/giovanaBritoOliveira/HighScore/blob/master/frontend/high_score/src/components/Comentario.js) percebi o seguinte cenário:

```js
this.state = {
    curtido: false,
    nao_curtido: false
}
```

Acredito que você não precisa desses dois estados `curtido` e `nao_curtido`, basta substituir os usos de `nao_curtido` para `!curtido`.

Assim, `curtido` pode assumir 3 valores:

- `undefined`: quando o usuário nem curtiu, nem "descurtiu" o comentário.
- `false`: quando o usuário "descurtiu" o comentário.
- `true`: quando o usuário curtiu o comentário.

Para isso, você pode iniciar o estado de curtido da seguinte forma:

```js
this.state = {
    curtido: undefined
}
```

**PS**: Lembre-se que `!curtido` vai retornar **verdadeiro** quando ele for `undefined`, então quando quiser checar se o usuário ainda não curtiu nem "descurtiu" o comentário, pode usar `if (curtido === undefined) { ... }` que funciona numa boa!

Que achas? :smile:

**Comment by g1ovanaqueiroz** [comment]
Faz muito sentido, Lucas! Valeu pelo toque, estarei atualizando embreve! :D
