### ISSUE TITLE
Sugestão para usar camelCase

### ISSUE THREAD

**Issue by jadsonluan** [giovanaBritoOliveira/HighScore#4]
Oi, @giovanaBritoOliveira ! 🎃 

Gostaria de sugerir que você considere usar camelCase invés de snake_case para as props dos componentes. Dessa forma, o teu código fica padronizado quanto à nomenclatura de propriedades do React.

Por exemplo [nesse componente](https://github.com/giovanaBritoOliveira/HighScore/blob/master/frontend/high_score/src/App.js)  a propriedade className (que é coisa do JSX mesmo) da div usa camelCase enquanto as propriedades de Comentario usam snake_case.

https://github.com/giovanaBritoOliveira/HighScore/blob/5bdf51afd5e06ebbe737a835d2b4d1e8bfe41786/frontend/high_score/src/App.js#L9-L11

É isso! Bom trabalho. 💯

**Comment by g1ovanaqueiroz** [comment]
Show, obrigada pela dica! ^^
