### ISSUE TITLE
Mover funções para dentro do componente

### ISSUE THREAD

**Issue by jadsonluan** [giovanaBritoOliveira/HighScore#5]
Oi, @giovanaBritoOliveira . 

Acredito que essas funções fariam mais sentido dentro do componente Comentario, uma vez que elas usam informação (curtido) que reside dentro dele.

https://github.com/giovanaBritoOliveira/HighScore/blob/8b10a8931e158efc199cddaa0425f80ce83c66a4/frontend/src/components/Comentario/Comentario.js#L21-L34

**Comment by g1ovanaqueiroz** [comment]
Valeu pela observação, Jadson. Vou corrigir isso em breve! ^^
