### ISSUE TITLE
criar constante para peças

### ISSUE THREAD

**Issue by ibiaalice** [giovanaBritoOliveira/HighScore#6]
Olá florzinha de cacto, então, notei que vc está setando todos os valores das peças quando vai chamar o component. Isso dá um trabalhão... que tal criar uma constante SCORE contendo o json de todas as peças e exporta-la junto ao component? ficaria bem mais legal e facilitado <3

**Comment by g1ovanaqueiroz** [comment]
Com uma issue tão fofinha dessa eu faço sim... haha
Muito obrigada, @ibiaalice ! ^^
